dataset_name: "merge"
datasets: ["yorkUrban", "tray"]
weights: [0.2,0.8]
gt_source_train: [
    "sold2_synth_yorkUrban_train_gt.h5",
    "sold2_synth_tray_train_gt.h5"]  # Fill with your own [wireframe, holicity] exported ground-truth
gt_source_test: [
                 "sold2_synth_yorkUrban_test_gt.h5",
                 "sold2_synth_tray_train_gt.h5"
]  # Fill with your own [wireframe, holicity] exported ground-truth
train_splits: [[],
               ["realsense_data_20220810-4", "realsense_data_20220810-1551",
                "realsense_data_20220810-1618", "realsense_data_20220810-1626"]
]
test_splits: [[],
              ["realsense_data_20220810-4", "realsense_data_20220810-1551",
               "realsense_data_20220810-1618", "realsense_data_20220810-1626"]
]
add_augmentation_to_all_splits: False
gray_scale: True
# Return type: (1) single (original version) (2) paired_desc
return_type: "single"
#return_type: "paired_desc"
# Number of points extracted per line
max_num_samples: 10
# Max number of training line points extracted in the whole image
max_pts: 1000
# Min distance between two points on a line (in  pixels)
min_dist_pts: 10
# Small jittering of the sampled points during training
jittering: 0
# Random seed
random_seed: 0
# Date preprocessing configuration.
preprocessing:
    resize: [128, 128]
    blur_size: 11
augmentation:
    random_scaling:
        enable: True
        range: [0.7, 1.5]
    photometric:
        enable: True
        primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
        params:
            random_brightness: {brightness: 0.2}
            random_contrast: {contrast: [0.3, 1.5]}
            additive_gaussian_noise: {stddev_range: [0, 10]}
            additive_speckle_noise: {prob_range: [0, 0.0035]}
            additive_shade:
                transparency_range: [-0.5, 0.5]
                kernel_size_range: [100, 150]
            motion_blur: {max_kernel_size: 3}
        random_order: True
    homographic:
        enable: True
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3
