### [Model parameters]
model_name: "lcnn_simple"
model_architecture: "simple"
# Backbone related config
backbone: "superpoint"
backbone_cfg:
  input_channel: 1 # Use RGB images or grayscale images.
  depth: 1
  num_stacks: 1
  num_blocks: 1
  num_classes: 5
# Junction decoder related config
junction_decoder: "superpoint_decoder"
junc_decoder_cfg:
# Heatmap decoder related config
heatmap_decoder: "pixel_shuffle"
heatmap_decoder_cfg:
# Shared configurations
grid_size: 8
keep_border_valid: True
# Threshold of junction detection
detection_thresh: 0.0153846 # 1/65
# Threshold of heatmap detection
prob_thresh: 0.5

### [Loss parameters]
weighting_policy: "dynamic"
# [Heatmap loss]
w_heatmap: 1.0
w_heatmap_class: 1
heatmap_loss_func: "cross_entropy"
heatmap_loss_cfg:
  policy: "static"
# [Junction loss]
w_junc: 1.0
junction_loss_func: "superpoint"
junction_loss_cfg:
  policy: "static"

### [Training parameters]
learning_rate: 0.00008
epochs: 200
train:
  batch_size: 256
  num_workers: 2
test:
  batch_size: 32
  num_workers: 4
disp_freq: 100
summary_freq: 20
save_freq: 5
max_ckpt: 150